# -*- coding: utf-8 -*-
"""spam-project-v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jF6NAmUPW_JH1s2ElOulq3wJQwgvQEH8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import joblib

import warnings
warnings.filterwarnings('ignore')

try:
    X_train = np.load('X_train.npy', allow_pickle=True)
    X_test = np.load('X_test.npy', allow_pickle=True)
    y_train = np.load('y_train.npy', allow_pickle=True)
    y_test = np.load('y_test.npy', allow_pickle=True)
    print(f"Eğitim Seti: {X_train.shape}")
    print(f"Test Seti: {X_test.shape}")
except FileNotFoundError:
    print("HATA: .npy dosyaları bulunamadı!")

models = {
    "Naive Bayes": MultinomialNB(),
    "SVM": SVC(kernel='linear', probability=True, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

results = []
plt.figure(figsize=(15, 5))

for i, (name, model) in enumerate(models.items()):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, zero_division=0),
        "Recall": recall_score(y_test, y_pred, zero_division=0),
        "F1-Score": f1_score(y_test, y_pred, zero_division=0)
    })

    cm = confusion_matrix(y_test, y_pred)
    plt.subplot(1, 3, i+1)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f"{name} Confusion Matrix")
    plt.xlabel("Tahmin")
    plt.ylabel("Gerçek")

plt.tight_layout()
plt.show()

results_df = pd.DataFrame(results)
display(results_df)

best_model_name = results_df.sort_values(by="F1-Score", ascending=False).iloc[0]["Model"]
print(f"En iyi model: {best_model_name}")

param_grids = {
    "Naive Bayes": {'alpha': [0.1, 0.5, 1.0, 2.0]},
    "SVM": {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf']},
    "Random Forest": {'n_estimators': [50, 100, 200], 'max_depth': [None, 10, 20], 'min_samples_split': [2, 5]}
}

if best_model_name in param_grids:
    base_model = models[best_model_name]
    grid_search = GridSearchCV(base_model, param_grids[best_model_name], cv=5, scoring='f1', n_jobs=-1)
    grid_search.fit(X_train, y_train)

    print(f"En iyi parametreler: {grid_search.best_params_}")
    final_model = grid_search.best_estimator_
else:
    final_model = models[best_model_name]

joblib.dump(final_model, 'best_model.joblib')
results_df.to_csv('results_table.csv', index=False)
print("Model ve sonuçlar kaydedildi.")

try:
    features_df = pd.read_csv('features_list.csv')
    feature_names = features_df.iloc[:, 0].values

    print(f"Toplam Özellik Sayısı: {len(feature_names)}")

    importances = None

    if hasattr(final_model, 'feature_importances_'):
        importances = final_model.feature_importances_
        print("Model Türü: Ağaç Tabanlı (Random Forest vb.) - Feature Importances kullanılıyor.")

    elif hasattr(final_model, 'coef_'):
        importances = np.abs(final_model.coef_[0])
        if hasattr(final_model, 'feature_log_prob_'): # Naive Bayes
             importances = final_model.feature_log_prob_[1] - final_model.feature_log_prob_[0]
             print("Model Türü: Naive Bayes - Log Olasılık Farkları kullanılıyor.")
        else:
             print("Model Türü: Lineer (SVM vb.) - Katsayılar (Coefficients) kullanılıyor.")

    else:
        print("Bu model türü için doğrudan özellik önem sıralaması yapılamıyor.")

    if importances is not None:
        if len(importances) != len(feature_names):
             print(f"UYARI: Model özellik sayısı ({len(importances)}) ile liste ({len(feature_names)}) uyuşmuyor!")
        else:
            feature_importance_df = pd.DataFrame({
                'Feature': feature_names,
                'Importance': importances
            })

            top_features = feature_importance_df.sort_values(by='Importance', ascending=False).head(20)

            plt.figure(figsize=(12, 8))
            sns.barplot(x='Importance', y='Feature', data=top_features, palette='viridis')
            plt.title(f'En Önemli 20 Kelime (Model: {best_model_name})')
            plt.xlabel('Önem Skoru / Etki')
            plt.ylabel('Kelime')
            plt.show()

            print("\nEn Önemli 20 Kelime:")
            print(top_features)

except FileNotFoundError:
    print("HATA: 'features_list.csv' dosyası bulunamadı!")
except Exception as e:
    print(f"Bir hata oluştu: {e}")